sudo: false

language: node_js
node_js: node

cache:
  directories:
    - $HOME/.npm
    - $HOME/.elm

install:
  - npm install

script:
  - npm run build
  - elm-test --verbose --compiler node_modules/.bin/elm
  - elm-verify-examples --elm-test node_modules/.bin/elm-test --elm-test-args="--verbose --compiler node_modules/.bin/elm"
