language: elm
elm:
    - "0.19.0"

branches:
    only:
        - staging
        - trying
        - master

script:
  - npm run build
  - elm-format --validate .
  - elm-test --verbose
  - elm-verify-examples --elm-test-args="--verbose"
