sudo: false

language: node_js
node_js: node

cache:
  directories:
    - $HOME/.npm
    - $HOME/.elm

install:
  - npm install

script:
  - npm run build
  - elm-test --verbose
  - elm-verify-examples
