language: elm

branches:
    only:
        - staging
        - trying
        - master

jobs:
    include:
        - stage: test
          name: "Elm tests"
          script:
            - npm install
            - npm run ci-format
            - npm run ci-test

        - stage: test
          name: "Webpack tests"
          script:
            - cd webpack
            - npm install
            - npm run build

        - stage: test
          name: "Parcel tests"
          script:
            - cd parcel
            - npm install
            - npm run build
