language: elm
elm:
    - "0.19.0"

branches:
    only:
        - staging
        - trying
        - master

script:
  - npm run build
  - npm run ci-format
  - npm run ci-test
  - npm run ci-test-examples
